### ISSUE TITLE
Missing default return values for several functions

### ISSUE THREAD

**Issue by jmscreation** [Frowsty/FrostUI#1]
**Function at Line 787**
`FUI_Element::get_selected_item()` does not have a default return type when `ui_type` is not a *dropdown*.
**Function at Line 794**
`FUI_Element::get_selected_items()` does not have a default return type when `ui_type` is not a *combolist*.
**Function at Line 835**
`FUI_Element::get_slider_value()` does not have a default return type.
**Function at Line 851**
`FUI_Element::get_inputfield_value()` does not have a default return type when `ui_type` is not an *inputfield*

In the event one of these happen, it results in undefined behavior. It would be recommended to at least have a controlled default value to return.

> Flowing off the end of a function ... results in undefined behavior

**Comment by Frowsty** [comment]
I have addressed the issues you pointed out :) Thank you
