### ISSUE TITLE
Inputfield_text and more, for input field

### ISSUE THREAD

**Issue by AlexFocu** [Frowsty/FrostUI#2]
Hello!
I'm trying to make ctrl+c and ctrl+v  commands for the input field, but I got confused in all the strings for it. I don't quite understand what all of these do (inputfield_text, displayed_text, text_out_of_view).

I want to make the string of the input field equal to another that is created when ctrl + c is pressed.

If I equal all the strings to my copied string, in the input field I get the last char duplicated
`               displayed_text = FUI_Window::sCopiedText;`
`                inputfield_text = FUI_Window::sCopiedText;`
`              text_out_of_view = FUI_Window::sCopiedText;`

![DA](https://user-images.githubusercontent.com/62220844/126326762-6d2cb8f6-d902-4ef8-ac06-2e4e2ac3b5e0.png)

Thanks!

**Comment by Frowsty** [comment]
Hi, basically `displayed_text` is the text that is currently visible in the inputfield, `text_out_of_view` Is the stored text that we cannot see in the inputfield and `inputfield_text` is the whole text that is visible and not visible. I haven’t gotten around to adding all the keyboard shortcuts for copying / pasting and moving the cursor etc and I’m not sure when I’ll have time to do so. If you understood what I mentioned above regarding the variables holding text you should be able to figure out how to go about adding copy / pasting

**Comment by AlexFocu** [comment]
> Hi, basically `displayed_text` is the text that is currently visible in the inputfield, `text_out_of_view` Is the stored text that we cannot see in the inputfield and `inputfield_text` is the whole text that is visible and not visible. I haven’t gotten around to adding all the keyboard shortcuts for copying / pasting and moving the cursor etc and I’m not sure when I’ll have time to do so. If you understood what I mentioned above regarding the variables holding text you should be able to figure out how to go about adding copy / pasting

Thank you!

Can you also explain how drop down works?
In code, I've got a tag and want to set it as the selected element in the dropdown, but I got confused with the std::pair for selected_elements.

![DA](https://user-images.githubusercontent.com/62220844/126381070-66cb8eda-7aa4-4e2b-b0a6-51f868f9c8a9.png)

**Comment by Frowsty** [comment]
So if I understand you correctly you want to set a default value for the drop_down correct? If so there's no real way of doing that yet. The code you sent above would only really apply on combolists as that's the only element making use of `selected_elements` the normal dropdown is not making use of `selected_elements` instead it's making use of `selected_element` when I come home from work today I'm more than happy to look into adding a default option for setting the starting / default value of a dropdown or combolist

**Comment by AlexFocu** [comment]
> So if I understand you correctly you want to set a default value for the drop_down correct? If so there's no real way of doing that yet. The code you sent above would only really apply on combolists as that's the only element making use of `selected_elements` the normal dropdown is not making use of `selected_elements` instead it's making use of `selected_element` when I come home from work today I'm more than happy to look into adding a default option for setting the starting / default value of a dropdown or combolist.
> 
> If you by any chance is in the OneLoneCoder discord channel I can also give you direct help in the #pixel-game-engine channel, my discord is `Frosty#0186`

Someone help me out. Here is the code if you want it.

![DA](https://user-images.githubusercontent.com/62220844/126391174-7864b35c-350f-4144-83fa-803a8f069742.png)

**Comment by Frowsty** [comment]
If you could elaborate on what you're trying to accomplish with the code I'm more than happy to help out

**Comment by Frowsty** [comment]
Since I am at work I can't test the code but if I'm not mistaken this following snippet should allow you to set a default value to a dropdown list
`
void FUI_Element::set_item(const std::string& item)
{
    if (ui_type == FUI_Type::DROPDOWN)
    {
        for(auto& element : elements)
        {
            if (element.second.second == item)
                selected_element = std::make_pair(scale, item);
        }
    }
    else
        std::cout << "Trying to add_item to wrong UI_TYPE\n";
}
`

**Comment by Frowsty** [comment]
Looks like the issue has been solved, closing this for now
