### ISSUE TITLE
Suggestion: make `color_scheme` field a pointer, in order to allow custom colour schemes

### ISSUE THREAD

**Issue by fhomolka** [Frowsty/FrostUI#5]
Title says it.

Currently, the only way to change the colour scheme is to edit the header itself.
This is fine for projects that copy over the header, but for projects that make use of git submodules, or simply do not want to edit any header code, the current way is not an option.

I'm willing to implement this myself, I'm just raising the suggestion first, to hear your opinion :)

**Comment by Frowsty** [comment]
You're very welcome to do the suggested changes and make a PR, however I must notify that the current color scheme system is only temporary and will be changed soon for something much simpler which will introduce new functions to change the color scheme
